export const SET_EVENT_SUCCESS = 'SET_EVENT_SUCCESS';
export const SET_EVENT_FAILURE = 'SET_EVENT_FAILURE';
export const SET_EVENTS_SUCCESS = 'SET_EVENTS_SUCCESS';
export const DELETE_EVENTS_SUCCESS = 'DELETE_EVENTS_SUCCESS';

export const LOGIN_TOKEN_SUCCESS = 'LOGIN_TOKEN_SUCCESS';
export const LOGIN_TOKEN_FAILURE = 'LOGIN_TOKEN_FAILURE';

export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
